<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */


/**
 * Implements hook_theme().
 */
function islandora_pdfjs_theme() {
  return array(
    'islandora_pdfjs' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-pdfjs',
      'variables' => array(
        'fedora_object' => NULL,
        'dsid' => NULL,
      ),
    ),
    'viewer' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/viewer',
      'variables' => array(
        'fedora_object' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_pdfjs_islandora_viewer_info() {
  return array(
    'islandora_pdfjs' => array(
      'label' => t('pdf.js Reader'),
      'description' => t('Mozilla pdf.js Reader.'),
      'configuration' => '',
      'callback' => 'islandora_pdfjs_viewer_callback',
      'model' => array(
        'islandora:sp_pdf',
        'islandora:bookCModel',
        'islandora:pageCModel',
        'islandora:newspaperIssueCModel'),
      'mimetype' => array('application/pdf'),
    ),
  );
}

/**
 * Implements hook_menu_alter().
 */
function islandora_pdfjs_menu_alter(&$items) {
  /* original code by patrick...@commonmediainc.com adapted for own use */
  $custom_info = array(
    'page callback' => '_islandora_pdfjs_islandora_view_datastream',
    'file' => 'islandora_pdfjs.module',
    'file path' => drupal_get_path('module', 'islandora_pdfjs'),
  );
  $paths = array(
    'islandora/object/%islandora_object/datastream/%islandora_datastream',
  );
  foreach($paths as $path) {
    if(!empty($items[$path])) {
      $items[$path] = array_merge($items[$path], $custom_info);
    }
  }
}

function _islandora_pdfjs_islandora_view_datastream(AbstractDatastream $datastream, $download = FALSE, $version = NULL) {
  module_load_include('inc', 'islandora', 'includes/datastream');

  $needsAcceptRangesHeader = ($datastream->mimetype === 'application/pdf');

  if ($needsAcceptRangesHeader) {
    header('Accept-Ranges: bytes');
  }

  islandora_view_datastream($datastream, $download, $version);
}

/**
 * Callback function for the viewer.
 *
 * @param array $params
 *   The params for the theme function 'islandora_pdfjs'.
 *
 * @param IslandoraAbstractObject $fedora_object
 *   The object that we are viewing.
 *
 * @return string
 *   HTML repersentation of the pdf.js Reader.
 */
function islandora_pdfjs_viewer_callback(array $params, $fedora_object = NULL) {
  $dsid = NULL;
  if (!empty($params['dsid']) && isset($fedora_object[$params['dsid']]) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $fedora_object[$params['dsid']])) {
    $dsid = $params['dsid'];
  }
  else {
    if (!empty($fedora_object['PDF']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $fedora_object['PDF'])) {
      $dsid = 'PDF';
    }
    elseif (!empty($fedora_object['PDFA']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $fedora_object['PDFA'])) {
      $dsid = 'PDFA';
    }
    elseif (isset($fedora_object['OBJ']) && $fedora_object['OBJ']->mimetype == 'application/pdf' && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $fedora_object['OBJ'])) {
      $dsid = 'OBJ';
    }
  }
  if ($dsid) {
    return theme('islandora_pdfjs', array('fedora_object' => $fedora_object, 'dsid' => $dsid));
  }
}
